import time
import pyautogui


# Follow pyautogui.moveTo(x,y) with a pyautogui.dragTo(x,y, button='left') that way it will drag the towers 

# print(pyautogui.size())
screenSize = pyautogui.size()
# print(screenSize[0], screenSize[1])

if ((screenSize[0] == 1920) and (screenSize[1] == 1080)) :
    print("Correct")
    time.sleep(5)
    pyautogui.click(966, 960)
    pyautogui.click(234, 98)
    pyautogui.click(944, 647)
    pyautogui.click(337, 95)
    pyautogui.moveTo(472,963)
    pyautogui.mouseDown(button='left')
    pyautogui.moveTo(605,688, 0.15)
    pyautogui.mouseUp(button='left')
    pyautogui.click(605,688)
    print("Basic Tower 1 Placed")
    time.sleep(11)
    pyautogui.click(640,483)
    print("Basic Tower Projectile Bounce Bought")
    time.sleep(8.9)
    pyautogui.click(644,436)
    print("Basic Tower Speed Bought")
    time.sleep(9.2)
    pyautogui.click(650,407)
    print("Basic Tower Range Bought")
    time.sleep(8.65)
    pyautogui.click(659,472)
    print("Basic Tower Strength Bought")
    time.sleep(7.6)
    pyautogui.moveTo(472,963)
    pyautogui.mouseDown(button='left')
    pyautogui.moveTo(611, 631, 0.15)
    pyautogui.mouseUp(button='left')
    print("Basic Tower 2 Placed")
    pyautogui.click(611,631)
    time.sleep(16)
    pyautogui.click(630,425)
    print("Basic Tower Projectile Bounce Bought")
    time.sleep(12.87)
    pyautogui.click(637,381)
    print("Basic Tower Speed Bought")
    # pyautogui.click(3640,964)
    time.sleep(7.53)
    pyautogui.click(647,414)
    # print()
