import time
import pyautogui


# Follow pyautogui.moveTo(x,y) with a pyautogui.dragTo(x,y, button='left') that way it will drag the towers 

# print(pyautogui.size())
screenSize = pyautogui.size()
# print(screenSize[0], screenSize[1])

if ((screenSize[0] == 1920) and (screenSize[1] == 1080)) :
    print("Correct")
    time.sleep(5)
    pyautogui.click(966, 960)
    pyautogui.click(234, 98)
    pyautogui.click(944, 647)
    pyautogui.click(337, 95)
    pyautogui.moveTo(472,963)
    pyautogui.mouseDown(button='left')
    pyautogui.moveTo(384, 635, 0.15)
    pyautogui.mouseUp(button='left')
    print("Basic Tower #1 Placed")
    time.sleep(11)
    pyautogui.click(384, 635)
    pyautogui.click(444, 427)
    print("Basic Tower Projectile Bounce Bought")
    time.sleep(9)
    pyautogui.click(439, 384)
    print("Basic Tower Speed Bought")
    time.sleep(9.2)
    pyautogui.click(443,420)
    print("Basic Tower Strength Bought")
    time.sleep(8.3)
    pyautogui.click(430, 348)
    print("Basic Tower Range Bought")
    pyautogui.moveTo(467,971)
    time.sleep(7.4)
    pyautogui.mouseDown(button='left')
    pyautogui.moveTo(495, 635, 0.15)
    pyautogui.mouseUp(button='left')
    print("Basic Tower #2 Placed")
    pyautogui.click(495,635)
    time.sleep(16.6)
    pyautogui.click(533,432)
    print("Basic Tower Projectile Bounce Bought")
    time.sleep(12.7)
    pyautogui.click(547,384)
    print("Basic Tower Speed Bought")
    time.sleep(7.55)
    pyautogui.click(541,413)
    print("Basic Tower Strength Bought")
    time.sleep(4.5)
    pyautogui.click(551,353)
    print("Basic Tower Range Bought")
    pyautogui.click(384, 635)
    time.sleep(23.1)
    pyautogui.click(432,455)
    print('Basic Tower #1 Projectile Bounce 8 bought')
    pyautogui.click(495, 635)
    time.sleep(9)
    pyautogui.click(544,447)
    print('Basic Tower #2 Projectile Bounce 8 bought')
    pyautogui.click(1531,560)
    time.sleep(26.5)
    pyautogui.moveTo(1031,962)
    pyautogui.mouseDown(button='left')
    pyautogui.moveTo(498, 528, 0.15)
    pyautogui.mouseUp(button='left')
    print("Bought Cannon Tower")
    time.sleep(2)
    pyautogui.click(384, 635)
    pyautogui.click(401,316)
    print("Sold Basic Tower #1")
    pyautogui.click(495, 635)
    pyautogui.click(510, 314)
    print("Sold Basic Tower #2")
    pyautogui.moveTo(1456,968)
    pyautogui.mouseDown(button='left')
    pyautogui.moveTo(384, 635, 0.15)
    pyautogui.mouseUp(button='left')
    print("Ultimate Tower Bought")
    time.sleep(2)
    pyautogui.click(498, 528)
    pyautogui.click(524,305)
    print("Cannon Tower Extra #1 Bought")
    time.sleep(15)
    pyautogui.click(530,299)
    print("Cannon Tower Direct Damage Explosion Bought")
    time.sleep(15)
    pyautogui.moveTo(890,965)
    pyautogui.mouseDown(button='left')
    pyautogui.moveTo(131, 839, 0.15)
    pyautogui.mouseUp(button='left')
    print('Sniper Tower Bought')
    pyautogui.click(131, 839)
    time.sleep(3)
    pyautogui.click(303,647)
    print("Sniper Tower Blinking Bought")
    time.sleep(10)
    pyautogui.click(318,556)
    print("Sniper Tower Speed Upgrade Bought")
    pyautogui.click(549,648)
    pyautogui.click(396,629)
    pyautogui.click(419,408)
    print("Ultimate Tower Extra Bought")
    time.sleep(46)
    pyautogui.click(439,396)
    print("Ultimate Tower Strength Upgrade Bought")
    pyautogui.click(601,670)
    pyautogui.moveTo(1452,960)
    time.sleep(34)
    pyautogui.mouseDown(button='left')
    pyautogui.moveTo(830,313 , 0.15)
    pyautogui.mouseUp(button='left')
    print("Ultimate Tower #2 Bought")
    time.sleep(6.5)
    pyautogui.moveTo(1032,961)
    pyautogui.mouseDown(button='left')
    pyautogui.moveTo(1092,541, 0.15)
    pyautogui.mouseUp(button='left')
    print('Cannon Tower #2 Bought')
    # pyautogui.click(3406, 846)
else:
    print("Commit Sepuku") 
